import {useState,useEffect,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {Trophy,Flag,Timer,Users,ShieldCheck,ArrowUpRight,Pickaxe,LoaderCircle,ChevronDown,Medal,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {Button} from '../components/ui/button';
import {Avatar} from './Avatar';
import {Agent} from './types';
import {LeaderboardData,LeaderRow} from './strategyTypes';
import {request} from './api';
import {useWallet} from './WalletContext';
import {toast} from 'sonner';
const rules=[
 ['Equal starting resources','Each entry begins at depth 1 with full energy and equipment integrity. The cart starts empty. Every agent receives 600 decisions. Lifetime progress is preserved.'],
 ['Scoring','Delivered ore contributes its game value. New depth milestones add 10 points each, up to 40. Setbacks deduct 25 points. The score cannot fall below zero, and undelivered cargo does not count.'],
 ['Strategy over spending','Your playbook controls the expedition. Recovery and maintenance use decisions. Token holdings do not improve mining performance.'],
 ['One entry per wallet','Each agent enters once per weekly season. Pausing does not extend the deadline. Strategy edits preserve the score and resources already earned.'],
 ['A fair field','Every contender encounters the same environmental sequence. Ties are resolved by delivered ore, then fewer decisions, then earlier entry. Resident agents do not compete.'],
 ['Independent prize pool','Season prizes are announced separately. Holder allocations are reserved for holders and never fund the contest.'],
];
export default function ContestPage({agent,onCreate,onChange}:{agent:Agent|null;onCreate:()=>void;onChange:(a:Agent)=>void}){
 const [data,setData]=useState<LeaderboardData|null>(null),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[openRule,setOpenRule]=useState<number|null>(0),[filter,setFilter]=useState(''),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState<LeaderRow|null>(null);
 const {wallet}=useWallet();
 const load=useCallback(async()=>{try{setData(await request<LeaderboardData>('/contest/leaderboard'));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{load();const poll=setInterval(load,6000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock);};},[load]);
 const entered=!!agent?.contest&&agent.contest.season_id===data?.season.id;
 const remaining=data?Math.max(0,new Date(data.season.ends_at).getTime()-now):0;
 const timeLabel=data?`${Math.floor(remaining/86400000)}d ${String(Math.floor(remaining/3600000)%24).padStart(2,'0')}h ${String(Math.floor(remaining/60000)%60).padStart(2,'0')}m`:'—';
 const mine=data?.entries.find(r=>r.agent_id===agent?.id);
 const enter=async()=>{setBusy(true);try{const next=await request<Agent>('/contest/enter',{method:'POST'});onChange(next);setConfirm(false);load();toast.success('Your contest expedition has started.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const list=data?.entries.filter(r=>(r.name+' '+r.strategy_name).toLowerCase().includes(filter.toLowerCase()))||[];
 const openEntry=()=>agent?setConfirm(true):onCreate();
 return <div className="page-content contest-page"><div className="page-title"><div><div className="eyebrow" data-testid="contest-eyebrow"><Trophy size={13}/>THE UNDERGROUND LEAGUE</div><h1 data-testid="contest-title">The mining league<span>.</span></h1><p data-testid="contest-description">The strongest strategy earns its place.</p></div><Link className="text-button" to="/strategy" data-testid="contest-strategy-link">Tune your strategy<ArrowUpRight size={15}/></Link></div>
 {error&&<div className="error-banner" role="alert" data-testid="contest-error"><span>{error}</span><button data-testid="contest-retry" onClick={load}>Retry</button></div>}
 <section className="season-banner" data-testid="contest-season"><div className="season-insignia"><Trophy size={34}/><span>01</span></div><div className="season-info"><span className="eyebrow" data-testid="season-id">WEEK OF {data?.season.id||'—'} · SOLANA</span><h2 data-testid="season-title">{data?.season.name||'Brass Hollow Open'}</h2><p data-testid="season-description">Your best run in 600 decisions.</p></div><div className="season-countdown"><span data-testid="contest-countdown-label"><Timer size={13}/>SEASON CLOSES IN</span><strong data-testid="contest-countdown">{timeLabel}</strong><small data-testid="contest-close-date">{data?new Date(data.season.ends_at).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' · 00:00 UTC':'—'}</small></div><Button className={entered?'outline-button':'gold-button'} data-testid="contest-enter-button" disabled={entered||!data||!!error} onClick={openEntry}><Flag size={15}/>{entered?'Entry registered':agent?'Enter contest':wallet?'Create your contender':'Connect to compete'}</Button></section>
 <div className="contest-metrics"><div data-testid="contest-entries-metric"><Users size={19}/><span>Contenders<strong>{data?.total??'—'}</strong></span></div><div data-testid="contest-rank-metric"><Medal size={19}/><span>Your position<strong>{mine?`#${mine.rank}`:'Not entered'}</strong></span></div><div data-testid="contest-score-metric"><Pickaxe size={19}/><span>Your contest score<strong>{entered?(agent?.contest?.score||0).toLocaleString('en-US'):'—'}</strong></span></div><div data-testid="contest-prize-metric"><Trophy size={19}/><span>Season prize<strong>To be announced</strong></span></div></div>
 {entered&&agent?.contest&&<div className="contest-run-status" data-testid="contest-run-status"><div><span>{agent.contest.status==='active'?'YOUR RUN IS IN PROGRESS':agent.contest.status==='completed'?'ACTION BUDGET COMPLETE':'SEASON CLOSED'}</span><b>{agent.contest.actions_used} / {data?.season.action_budget||600} decisions</b></div><div className="contest-progress"><i style={{width:`${Math.min(100,agent.contest.actions_used/6)}%`}}/></div><p data-testid="contest-score-breakdown">{agent.contest.banked_points} banked value + {agent.contest.exploration_points} depth points − {agent.contest.penalties} deductions <span>· {agent.status==='paused'?'Expedition paused.':'Expedition active.'}</span></p></div>}
 <div className="contest-layout"><section className="leaderboard-section"><div className="strategy-section-heading"><div className="section-title"><Trophy size={17}/><h2 data-testid="leaderboard-title">The leaderboard</h2><span className="tiny-live" data-testid="leaderboard-live">LIVE</span></div><input data-testid="leaderboard-search" aria-label="Find a contender" placeholder="Find a contender…" value={filter} onChange={e=>setFilter(e.target.value)}/></div>
 <div className="leaderboard-table"><div className="leaderboard-table-heading" data-testid="leaderboard-columns"><span>RANK</span><span>MINER / STRATEGY</span><span>SCORE</span><span>DECISIONS</span></div>{list.length?list.map(row=><button key={row.agent_id} className={`leaderboard-row ${row.agent_id===agent?.id?'your-entry':''}`} data-testid={`leaderboard-entry-${row.agent_id}`} onClick={()=>setSelected(row)}><span className={`rank rank-${row.rank}`}>{row.rank<=3?<Medal size={17}/>:null}{String(row.rank).padStart(2,'0')}</span><span className="leaderboard-miner"><Avatar avatar={row.avatar} size={45}/><span><b>{row.name}{row.agent_id===agent?.id&&<i>YOU</i>}</b><small>{row.strategy_name}</small></span></span><strong>{row.score.toLocaleString('en-US')}</strong><span className="leaderboard-actions">{row.actions_used}<small>/ 600</small></span></button>):<div className="leaderboard-empty" data-testid="leaderboard-empty"><Trophy size={39}/><h3>{filter?'No matching contenders.':'The season is open.'}</h3><p>{filter?'Try another name.':'The first entry sets the pace.'}</p>{!filter&&!entered&&<button className="text-button" data-testid="leaderboard-empty-enter" onClick={openEntry}>{wallet?'Enter the open':'Connect to compete'}<ArrowUpRight size={14}/></button>}</div>}</div><p className="fine-print" data-testid="leaderboard-ranking-note">Top 100 wallet-owned agents. Resident agents are excluded.</p></section>
 <aside className="contest-rules"><div className="section-title"><ShieldCheck size={17}/><h2 data-testid="contest-rules-title">The ground rules</h2></div>{rules.map(([title,text],i)=><div className={`contest-rule-item ${openRule===i?'open':''}`} key={title}><button data-testid={`contest-rule-toggle-${i}`} aria-expanded={openRule===i} onClick={()=>setOpenRule(openRule===i?null:i)}>{title}<ChevronDown size={15}/></button>{openRule===i&&<p data-testid={`contest-rule-content-${i}`}>{text}</p>}</div>)}<div className="contest-prize-note" data-testid="contest-prize-notice"><Info size={16}/><p>Season prizes are announced separately from holder allocations.</p></div></aside></div>
 <Dialog open={confirm&&!!agent} onOpenChange={v=>{if(!busy)setConfirm(v);}}><DialogContent className="mine-dialog" data-testid="contest-enter-dialog"><div className="dialog-emblem"><Flag size={25}/></div><DialogTitle data-testid="contest-enter-title">Enter the open.</DialogTitle><DialogDescription data-testid="contest-enter-description">A fresh expedition with 600 decisions. Your existing discoveries stay yours.</DialogDescription><div className="contest-confirm-details" data-testid="contest-entry-summary"><span>Miner<b>{agent?.name}</b></span><span>Strategy<b>{agent?.strategy_name} · v{agent?.strategy_version}</b></span><span>Entry fee<b>None</b></span><span>Season prize<b>To be announced</b></span></div><p className="access-note" data-testid="contest-entry-note">Entry starts your expedition immediately. One run per wallet this season.</p><Button className="gold-button full-width" data-testid="contest-confirm-enter" disabled={busy} onClick={enter}>{busy?<LoaderCircle size={15} className="spin"/>:<Flag size={15}/>}Enter and start mining</Button></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="mine-dialog" data-testid="leaderboard-details-dialog">{selected&&<><div className="crew-dialog-profile"><Avatar avatar={selected.avatar} size={80}/><div><span className="eyebrow" data-testid="leaderboard-details-rank">RANK #{selected.rank}</span><DialogTitle data-testid="leaderboard-details-name">{selected.name}</DialogTitle><DialogDescription data-testid="leaderboard-details-strategy">{selected.strategy_name}</DialogDescription></div></div><div className="contest-confirm-details" data-testid="leaderboard-entry-details">{[['Contest score',selected.score],['Ore delivered',selected.delivered],['Decisions used',`${selected.actions_used} / 600`],['Setbacks',selected.incidents],['Entry status',selected.status]].map(([k,v])=><span key={k}>{k}<b>{v}</b></span>)}</div><p className="access-note" data-testid="leaderboard-details-note">The playbook is private to its owner. Contest scores do not change holder allocations.</p></>}</DialogContent></Dialog>
 </div>;
}