import {useState} from 'react';
import {BookOpen,Compass,Pickaxe,Truck,Flame,Wrench,Tent,ChevronDown,Gem,LockKeyhole,Check} from 'lucide-react';
import {Agent} from './types';
const catalog=[{id:'pyrite',name:'Pyrite cluster',kind:'THE FIRST GLINT',color:'#cfad67',cycles:1,description:'A brass-colored mineral from the shallow seams of Brass Hollow.'},{id:'quartz',name:'Smoky quartz',kind:'A QUIET DISCOVERY',color:'#abbab9',cycles:3,description:'Translucent crystal found beyond the western shaft.'},{id:'azurite',name:'Azurite bloom',kind:'FROM THE DEEP',color:'#6fa8b3',cycles:6,description:'A deep-blue formation from the oldest tunnels in the mine.'}];
export const Collection=({agent}:{agent:Agent|null})=><div className="collection-grid">{catalog.map(c=>{const unlocked=agent?.discoveries.includes(c.id);return <article className={`collection-item ${unlocked?'unlocked':''}`} key={c.id} data-testid={`collection-${c.id}`}><div className="crystal-art" style={{'--crystal-color':c.color} as React.CSSProperties}><i/><i/><i/><i/><i/></div><span className="eyebrow">{c.kind}</span><h3 data-testid={`collection-name-${c.id}`}>{c.name}</h3><p data-testid={`collection-description-${c.id}`}>{c.description}</p><span className="collection-unlock" data-testid={`collection-status-${c.id}`}>{unlocked?<Check size={12}/>:<LockKeyhole size={12}/>} {unlocked?'Discovered':`${c.cycles} completed expedition${c.cycles>1?'s':''}`}</span></article>;})}</div>;
const faqs=[
 ['Does my agent keep working when I leave?','Yes. Active agents continue their expeditions after you close the browser or disconnect. Progress belongs to your wallet account. An agent pauses if its holder access ends.'],
 ['Do mining scores increase my GLDX share?','No. Holder allocations are proportional to eligible Agent Miner holdings. Contest scores never change that share.'],
 ['How do strategy rules work?','Rules run from top to bottom. The first matching rule determines the next action. ALL and ANY groups combine conditions. Critical energy or equipment limits take priority over your custom rules.'],
 ['What changes my contest score?','Delivered ore adds its game value. Each new depth adds 10 points, up to 40 per run. Setbacks deduct 25 points. Undelivered cargo earns nothing. Each entry receives 600 decisions.'],
 ['Can I edit a strategy during a contest?','Yes. Saved changes affect future decisions without resetting your score or resources. The workbench evaluates a draft separately from your active expedition.'],
 ['Who can enter a contest?','Agent Miner holders with a wallet-owned agent. Each wallet receives one entry per season. Autonomous resident agents stay outside the leaderboard.'],
 ['Do I need a wallet to visit?','The mine and standings are public. Connecting a wallet with holder access unlocks your agent and its strategy. Your agent remains linked to that wallet when you return.'],
 ['What is GLDX?','GLDX is Gold xStock on Solana, a tokenized tracker of SPDR Gold Shares. It does not represent direct ownership of physical gold or ETF shares. Issuer and jurisdiction restrictions apply.'],
 ['Are contest prizes part of holder rewards?','No. Contest prizes use a separate project or sponsor pool. Holder allocations are reserved for holders.'],
 ['Is staking required?','No. Agent Miner uses holder access without locking tokens. Holding more does not buy a mining advantage.'],
];
export default function Guide({agent}:{agent:Agent|null}){
 const [open,setOpen]=useState<number|null>(0);
 return <div className="page-content"><div className="page-title"><div><div className="eyebrow" data-testid="guide-eyebrow">BRASS HOLLOW ARCHIVE</div><h1 data-testid="guide-title">The Field Guide<span>.</span></h1><p data-testid="guide-description">Notes from the underground.</p></div><BookOpen className="page-symbol" size={36}/></div>
 <section className="guide-cycle"><h2 data-testid="cycle-title">The mining cycle</h2><div className="cycle-flow">{[{icon:Tent,title:'Basecamp',description:'Pack supplies.'},{icon:Compass,title:'Survey',description:'Find a promising seam.'},{icon:Pickaxe,title:'Mine',description:'Uncover the ore.'},{icon:Truck,title:'Haul',description:'Bring the cart home.'},{icon:Flame,title:'Refine',description:'Deliver the haul.'},{icon:Wrench,title:'Maintain',description:'Care for the tools.'}].map((s,i)=><div key={s.title} data-testid={`cycle-step-${i}`}><span className="cycle-number">0{i+1}</span><s.icon size={25}/><h3>{s.title}</h3><p>{s.description}</p></div>)}</div></section>
 <section className="collection-section"><div className="collection-heading"><div className="section-title"><Gem size={19}/><h2 data-testid="collection-title">The discovery cabinet</h2></div><span className="neutral-badge" data-testid="collection-count">{agent?.discoveries.length||0} / 3 discovered</span></div><Collection agent={agent}/><p className="fine-print" data-testid="collection-financial-note">Discoveries are collectibles. They do not increase GLDX allocations.</p></section>
 <section className="faq-section"><div><span className="eyebrow">FIELD NOTES</span><h2 data-testid="faq-title">Before you head<br/>underground.</h2></div><div>{faqs.map(([question,answer],i)=><div className={`faq-item ${open===i?'open':''}`} key={i}><button data-testid={`faq-question-${i}`} onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{question}<ChevronDown size={17}/></button>{open===i&&<p data-testid={`faq-answer-${i}`}>{answer}</p>}</div>)}</div></section></div>;
}