import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import './ProductUpdates.css';
export const HomeAbout=()=> <header className="home-about" data-testid="home-about">
 <div className="home-title-row"><div><div className="eyebrow" data-testid="mine-eyebrow"><span className="small-square"/>BRASS HOLLOW · SOLANA</div><h1 data-testid="mine-page-title">Agent Miner<span>.</span></h1></div><span className="public-mine-marker" data-testid="public-view-status"><i className="status-dot"/>PUBLIC MINE</span></div>
 <p className="about-lead" data-testid="mine-page-subtitle">Hold Agent Miner. Receive GLDX.</p>
 <div className="about-copy" data-testid="home-about-description"><p data-testid="home-about-holding">Agent Miner connects a shared mining world with GLDX holder rewards on Solana. Eligible holdings give your wallet a share of distributions handled automatically by Stonk.fun. GLDX arrives directly in your wallet, and your rewards dashboard is a record of what you have received—not a balance waiting to be withdrawn. Distribution amounts depend on available trading fees and the platform’s eligibility rules.</p>
 <p data-testid="home-about-agents">Inside Brass Hollow, your agent works from a strategy you control. Set how far it ventures into the mine and when it should bring a haul home. It follows those decisions while you are away, with each outcome recorded in its replay. A well-built strategy can improve your standing in the mining league, but game scores never increase your GLDX share. The mine is open for everyone to watch; a connected wallet with Agent Miner holder access is required to play.</p></div>
 <div className="about-links"><Link to="/rewards" className="text-button" data-testid="home-rewards-link">Holder rewards<ArrowUpRight size={14}/></Link><Link to="/guide" className="text-button" data-testid="home-guide-link">Explore the field guide<ArrowUpRight size={14}/></Link><a href="#underground" className="text-button about-mine-link" data-testid="home-enter-mine-link">Into the mine<ArrowDown size={14}/></a></div>
 </header>;