import {useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {History,ArrowUpRight,Play,Pause,SkipBack,SkipForward,RotateCcw,RefreshCw,ChevronUp,LoaderCircle,Wallet,Pickaxe} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Agent} from './types';
import {accessToken,request} from './api';
import {useWallet} from './WalletContext';
import {DecisionReplay,ReplayPageData,actionNames,signed} from './replayTypes';
import {ReplayDecision} from './ReplayDecision';
import './Replay.css';

export default function ReplayPage({agent,onCreate,onConnect}:{agent:Agent|null;onCreate:()=>void;onConnect:()=>void}){
 const {wallet,loading:walletLoading}=useWallet(),agentId=agent?.id;
 const [data,setData]=useState<ReplayPageData|null>(null),[entries,setEntries]=useState<DecisionReplay[]>([]),[selectedId,setSelectedId]=useState(''),[scope,setScope]=useState('all'),[change,setChange]=useState('all'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1);
 const generation=useRef(0),requestSequence=useRef(0);
 const load=useCallback(async(before?:number)=>{
  if(!agentId)return;
  const current=generation.current,sequence=++requestSequence.current,token=accessToken();setLoading(true);setError('');
  try{
   const result=await request<ReplayPageData>(`/agent/replay?scope=${scope}&change=${change}&limit=80${before?`&before=${before}`:''}`);
   if(current!==generation.current||sequence!==requestSequence.current||token!==accessToken())return;
   setData(result);setEntries(old=>before?[...result.entries,...old.filter(e=>!result.entries.some(n=>n.id===e.id))]:result.entries);
   if(!before)setSelectedId(old=>result.entries.some(e=>e.id===old)?old:result.entries[0]?.id||'');
  }catch(e){if(current===generation.current&&sequence===requestSequence.current)setError((e as Error).message);}finally{if(current===generation.current&&sequence===requestSequence.current)setLoading(false);}
 },[agentId,scope,change]);
 useEffect(()=>{generation.current+=1;setEntries([]);setData(null);setSelectedId('');setPlaying(false);load();return()=>{generation.current+=1;};},[load]);
 useEffect(()=>{if(!agentId||data?.recorded_total!==0||agent?.status!=='active')return;const timer=setInterval(()=>load(),2000);return()=>clearInterval(timer);},[agentId,agent?.status,data?.recorded_total,load]);
 const index=Math.max(0,entries.findIndex(e=>e.id===selectedId)),entry=entries[index];
 useEffect(()=>{if(!playing)return;if(index>=entries.length-1){setPlaying(false);return;}const timer=setTimeout(()=>setSelectedId(entries[index+1].id),1800/speed);return()=>clearTimeout(timer);},[playing,index,entries,speed]);
 const select=(i:number)=>{setPlaying(false);setSelectedId(entries[Math.min(entries.length-1,Math.max(0,i))]?.id||'');};
 const toggle=()=>{if(!playing&&index===entries.length-1)setSelectedId(entries[0].id);setPlaying(v=>!v);};
 return <div className="page-content replay-page"><div className="page-title"><div><div className="eyebrow" data-testid="replay-eyebrow">THE EXPEDITION RECORD</div><h1 data-testid="replay-title">Decision replay<span>.</span></h1><p data-testid="replay-description">Every decision has a reason. Every point has a history.</p></div><Link to="/strategy" className="text-button" data-testid="replay-edit-strategy">Edit strategy<ArrowUpRight size={14}/></Link></div>
 <div className="agent-subnav"><Link to="/agent" data-testid="replay-overview-tab">Overview</Link><Link to="/strategy" data-testid="replay-strategy-tab">Strategy</Link><span className="active" data-testid="replay-current-tab"><History size={14}/>Replay</span><Link to="/leaderboard" data-testid="replay-contest-tab">Contest</Link></div>
 {!wallet||!agent?<div className="strategy-no-agent" data-testid="replay-access-gate"><History size={36}/><h2 data-testid="replay-access-title">Your agent’s story, decision by decision.</h2><p data-testid="replay-access-description">{wallet?'An expedition starts with your own agent.':'Connect the wallet that owns your agent to open its record.'}</p><Button disabled={walletLoading} className="gold-button" data-testid="replay-connect-or-create" onClick={wallet?onCreate:onConnect}>{wallet?<Pickaxe size={15}/>:<Wallet size={15}/>}{wallet?'Create agent':'Connect wallet'}</Button></div>:<>
 <div className="replay-toolbar"><div className="replay-filters"><label>Expedition<select data-testid="replay-scope-filter" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All decisions</option><option value="contest">Contest only</option><option value="expedition">Open mine only</option></select></label><label>Score change<select data-testid="replay-change-filter" value={change} onChange={e=>setChange(e.target.value)}><option value="all">Any outcome</option><option value="gain">Points gained</option><option value="loss">Points lost</option><option value="steady">No score change</option></select></label></div><button disabled={loading} title="Refresh decisions" aria-label="Refresh decisions" data-testid="replay-refresh" className="replay-icon-button" onClick={()=>{setPlaying(false);load();}}><RefreshCw size={16} className={loading?'spin':''}/></button></div>
 {error&&<div className="error-banner" role="alert" data-testid="replay-error"><span>{error}</span><button data-testid="replay-retry" onClick={()=>load()}>Retry</button></div>}
 {!entry?<div className="replay-empty" data-testid="replay-empty">{loading?<LoaderCircle size={32} className="spin"/>:<History size={32}/>}<h2 data-testid="replay-empty-title">{loading?'Opening the expedition record…':data?.recorded_total?'No decisions match these filters.':'The first decision is still ahead.'}</h2><p data-testid="replay-empty-description">{data?.recorded_total?'Choose another outcome to see more of this expedition.':agent.status==='active'?'Your next mining decision will appear here.':'Start or resume an expedition to record its next decision.'}</p>{!data?.recorded_total&&agent.status!=='active'&&<Link className="text-button" to="/agent" data-testid="replay-start-expedition">Back to your agent<ArrowUpRight size={14}/></Link>}</div>:<>
 <div className="replay-playback" data-testid="replay-playback"><div className="replay-transport"><button className="replay-icon-button" data-testid="replay-restart" title="First loaded decision" aria-label="First loaded decision" disabled={index===0} onClick={()=>select(0)}><RotateCcw size={16}/></button><button className="replay-icon-button" data-testid="replay-previous" title="Previous decision" aria-label="Previous decision" disabled={index===0} onClick={()=>select(index-1)}><SkipBack size={17}/></button><button className="replay-play" data-testid="replay-play-pause" title={playing?'Pause replay':'Play replay'} aria-label={playing?'Pause replay':'Play replay'} aria-pressed={playing} disabled={entries.length<2} onClick={toggle}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><button className="replay-icon-button" data-testid="replay-next" title="Next decision" aria-label="Next decision" disabled={index===entries.length-1} onClick={()=>select(index+1)}><SkipForward size={17}/></button></div><div className="replay-scrubber"><span data-testid="replay-position">{index+1} / {entries.length} loaded decisions</span><input type="range" aria-label="Replay timeline" min={0} max={Math.max(1,entries.length-1)} disabled={entries.length<2} value={index} onChange={e=>select(Number(e.target.value))} data-testid="replay-timeline"/></div><select aria-label="Replay speed" data-testid="replay-speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></div>
 <div className="replay-layout"><aside className="replay-list-panel"><div className="replay-list-heading"><span data-testid="replay-agent-name">{agent.name}’s record</span><span data-testid="replay-record-count">{data?.total??entries.length} decisions</span></div>{data?.has_more&&<button className="text-button replay-earlier" disabled={loading} data-testid="replay-load-earlier" onClick={()=>{setPlaying(false);load(data.next_before!);}}><ChevronUp size={14}/>Load earlier decisions</button>}<div className="replay-decision-list" data-testid="replay-decision-list">{entries.map(e=><button key={e.id} data-testid={`replay-entry-${e.sequence}`} className={e.id===entry.id?'selected':''} aria-pressed={e.id===entry.id} onClick={()=>{setPlaying(false);setSelectedId(e.id);}}><span className="replay-list-number">{e.sequence}</span><span className="replay-list-info"><b>{actionNames[e.action]||e.action}</b><small>{e.scope==='contest'?'Contest':'Open mine'} · {new Date(e.created_at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</small></span><strong className={e.score_delta>0?'positive':e.score_delta<0?'negative':'neutral'}>{signed(e.score_delta)}</strong></button>)}</div></aside><ReplayDecision entry={entry} agent={agent}/></div>
 </>}
 </>}
 </div>;
}