import {ArrowRight,GitBranch,Pickaxe,ShieldCheck} from 'lucide-react';
import {Avatar} from './Avatar';
import {Agent} from './types';
import {DecisionReplay,ReplayState,actionNames,signed} from './replayTypes';
const resources:{key:keyof ReplayState;label:string;unit:string}[]=[{key:'energy',label:'Energy',unit:'%'},{key:'tool',label:'Tool integrity',unit:'%'},{key:'cargo',label:'Cart load',unit:'%'},{key:'depth',label:'Depth',unit:''},{key:'quality',label:'Vein quality',unit:'%'},{key:'delivered',label:'Ore delivered',unit:''}];
export const ReplayDecision=({entry,agent}:{entry:DecisionReplay;agent:Agent})=> <article className="replay-decision" data-testid="replay-decision-detail">
 <div className="replay-decision-heading"><div className="replay-miner"><Avatar avatar={agent.avatar} size={62}/><div><span className="eyebrow" data-testid="replay-selected-sequence">DECISION {entry.sequence}</span><h2 data-testid="replay-action">{actionNames[entry.action]||entry.action}</h2><time data-testid="replay-timestamp" dateTime={entry.created_at}>{new Date(entry.created_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></div></div><span className={`replay-delta ${entry.score_delta>0?'positive':entry.score_delta<0?'negative':'neutral'}`} data-testid="replay-score-delta">{signed(entry.score_delta)}<small>POINTS</small></span></div>
 <div className="replay-context" data-testid="replay-strategy-context"><GitBranch size={13}/><span>{entry.strategy_name} · v{entry.strategy_version}</span><span className="neutral-badge" data-testid="replay-scope">{entry.scope==='contest'?`CONTEST · ${entry.season_id}`:'OPEN EXPEDITION'}</span></div>
 <div className="replay-reason"><span className="eyebrow" data-testid="replay-reason-label">WHY THIS DECISION</span><p data-testid="replay-reason">{entry.reason}</p><span className="replay-outcome" data-testid="replay-outcome"><Pickaxe size={15}/>{entry.message}</span></div>
 <div className="replay-score"><div><span data-testid="replay-score-label">{entry.scope==='contest'?'Contest score':'Expedition score'}</span><strong data-testid="replay-score-transition">{entry.score_before.toLocaleString('en-US')}<ArrowRight size={20}/>{entry.score_after.toLocaleString('en-US')}</strong></div><p data-testid="replay-score-explanation">{entry.score_explanation}</p></div>
 <div className="replay-breakdown" data-testid="replay-score-breakdown"><span>Delivered value <b data-testid="replay-banked-delta">{signed(entry.banked_delta)}</b></span><span>Depth milestone <b data-testid="replay-depth-delta">{signed(entry.exploration_delta)}</b></span><span>Setback deduction <b data-testid="replay-penalty-delta">{entry.penalty_delta?`−${entry.penalty_delta}`:'0'}</b></span></div>
 <section className="replay-resources"><div className="replay-resource-heading" data-testid="replay-resource-headings"><h3>Resources</h3><span>BEFORE</span><span>AFTER</span></div>{resources.map(r=><div className="replay-resource" key={r.key} data-testid={`replay-resource-${r.key}`}><span>{r.label}</span><b>{entry.before[r.key]}{r.unit}</b><b className={entry.before[r.key]!==entry.after[r.key]?'changed':''}>{entry.after[r.key]}{r.unit}</b></div>)}</section>
 <p className="replay-financial-note" data-testid="replay-financial-boundary"><ShieldCheck size={14}/>Mining points do not affect GLDX distributions.</p>
 </article>;