import {Coins,ArrowUpRight,Info,Clock3,ExternalLink,ReceiptText,Wallet,ArrowDownLeft,RefreshCw,Trophy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../components/ui/button';
import {useRewardData} from './rewardData';
import {shortAddress} from './WalletContext';
import './ProductUpdates.css';

export const PoolPanel=()=>{
 const {history,wallet,error}=useRewardData();
 return <section className="pool-panel" data-testid="mining-pool-panel"><div className="panel-heading"><div className="section-title"><ArrowDownLeft size={16}/><h2 data-testid="pool-panel-title">Holder Rewards</h2></div><Link data-testid="pool-details-link" to="/rewards" title="View GLDX receipts" aria-label="View GLDX receipts"><ArrowUpRight size={16}/></Link></div><div className="pool-body"><div className="pool-label" data-testid="received-gldx-label">GLDX RECEIVED<span className="gld-symbol">G</span></div><strong className="unavailable-value" data-testid="received-gldx-value">{history?.total_received??'—'} <small>GLDX</small></strong><span className="pool-status" data-testid="received-gldx-status">Automatic distributions · Stonk.fun</span><div className="pool-line"><span>Recorded transfers</span><span data-testid="sidebar-receipt-count">{history?.receipt_count??'—'}</span></div>{error?<p className="form-error" data-testid="sidebar-rewards-error">{error}</p>:<p className="pool-disclaimer" data-testid="pool-disclaimer"><Info size={12}/>{wallet?'Delivered directly to your wallet. Mining scores do not change holder rewards.':'Connect your wallet to view your GLDX receipts.'}</p>}<Link to="/rewards" className="text-button receipt-history-link" data-testid="sidebar-view-receipts">View receipt history<ArrowUpRight size={13}/></Link></div></section>;
};

export default function Rewards({onConnect}:{onConnect:()=>void}){
 const {info,history,error,loading,refresh,wallet}=useRewardData();
 const lastReceived=history?.last_received_at?new Date(history.last_received_at).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
 return <div className="page-content rewards-receipts"><div className="page-title"><div><div className="eyebrow" data-testid="rewards-eyebrow">DELIVERED TO YOUR WALLET</div><h1 data-testid="rewards-title">Your GLDX receipts<span>.</span></h1><p data-testid="rewards-intro">Holder distributions from Stonk.fun, recorded on Solana.</p></div><span className="neutral-badge" data-testid="reward-asset-badge"><Coins size={15}/>GLDX · Solana</span></div>
 <div className="receipt-wallet-bar" data-testid="receipt-wallet-bar"><div><Wallet size={17}/><span data-testid="rewards-wallet-address">{wallet?shortAddress(wallet.address):'No wallet connected'}</span>{wallet&&<small data-testid="receipt-wallet-provider">{wallet.provider}</small>}</div>{wallet?<button title="Refresh receipts" aria-label="Refresh receipts" className="text-button" data-testid="refresh-receipts" onClick={refresh} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/>Refresh</button>:<Button className="gold-button" data-testid="rewards-connect-wallet" onClick={onConnect}><Wallet size={14}/>Connect wallet</Button>}</div>
 {error&&<div className="error-banner" role="alert" data-testid="rewards-error"><span>{error}</span><button data-testid="rewards-retry" onClick={refresh}>Retry</button></div>}
 <div className="reward-metrics">{[{label:'Total received',icon:ArrowDownLeft,value:history?.total_received??'—',sub:'GLDX · Recorded receipts'},{label:'Transfers received',icon:ReceiptText,value:history?.receipt_count??'—',sub:'Confirmed receipt records'},{label:'Latest distribution',icon:Clock3,value:lastReceived,sub:'Most recent receipt'}].map((m,i)=><section key={m.label} data-testid={`reward-metric-${i}`}><div className="metric-top"><m.icon size={18}/><span>{m.label}</span></div><strong data-testid={`reward-value-${i}`}>{m.value}</strong><small>{m.sub}</small></section>)}</div>
 <section className="distribution-section receipt-ledger"><div className="receipt-ledger-heading"><div className="section-title"><ReceiptText size={18}/><h2 data-testid="distribution-title">Receipt history</h2><span className="neutral-badge" data-testid="distribution-count">{history?.receipt_count??0} records</span></div><span className="receipt-network" data-testid="receipt-delivery-mode"><i className="status-dot"/>Automatic distribution</span></div>
 <div className="receipt-columns" data-testid="receipt-columns"><span>RECEIVED</span><span>AMOUNT</span><span>SOURCE</span><span>TRANSACTION</span></div>
 <div className="ledger-empty" data-testid="distribution-empty"><ReceiptText size={30}/><h3 data-testid="receipts-empty-title">{loading?'Loading receipt history…':error?'Receipt history unavailable':wallet?'No receipts recorded':'Your wallet’s reward history'}</h3><p data-testid="receipts-empty-description">{error?'Try refreshing to retrieve your records.':wallet?'There are no GLDX distribution records for this wallet.':'Connect a wallet to view its recorded GLDX distributions.'}</p></div>
 </section>
 <div className="receipt-explanation"><section><div className="section-title"><ArrowDownLeft size={19}/><h2 data-testid="automatic-rewards-title">Rewards arrive automatically</h2></div><p data-testid="automatic-rewards-description">Stonk.fun handles distributions to eligible Agent Miner holders. This dashboard records GLDX that has reached your wallet; it does not hold your funds or initiate payouts. Distribution timing and amounts are determined by Stonk.fun.</p>{info?.platform_url&&<a href={info.platform_url} target="_blank" rel="noreferrer" data-testid="stonk-reference-link" className="text-button">Stonk.fun<ExternalLink size={13}/></a>}</section><section><div className="section-title"><Trophy size={19}/><h2 data-testid="independent-rewards-title">Independent of the mining league</h2></div><p data-testid="independent-rewards-description">Your agent’s performance affects its contest standing, not your GLDX entitlement. Holding does not require an active expedition. Game ore is not a token balance.</p><Link className="text-button" to="/leaderboard" data-testid="rewards-contest-link">View the contest<ArrowUpRight size={13}/></Link></section></div>
 <div className="reward-footnotes" data-testid="reward-risk-notice"><Info size={15}/><p>GLDX is Gold xStock, a tokenized tracker of SPDR Gold Shares, not direct ownership of physical gold. Distribution amounts and timing are not guaranteed. Platform eligibility and issuer restrictions apply.</p></div></div>;
}