import {useEffect,useState} from 'react';
import {Coins,ArrowUpRight,LockKeyhole,Info,Clock3,ShieldCheck,ExternalLink,ReceiptText,Wallet,Scale,Trophy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../components/ui/button';
import {request} from './api';
import {Reward} from './types';
export const PoolPanel=()=> <section className="pool-panel" data-testid="mining-pool-panel"><div className="panel-heading"><div className="section-title"><Coins size={16}/><h2 data-testid="pool-panel-title">Holder Rewards</h2></div><Link data-testid="pool-details-link" to="/rewards" title="Holder reward details" aria-label="Holder reward details"><ArrowUpRight size={16}/></Link></div><div className="pool-body"><div className="pool-label" data-testid="claimable-label">CLAIMABLE GLDX <span className="gld-symbol">G</span></div><strong className="unavailable-value" data-testid="claimable-value">— <small>GLDX</small></strong><span className="pool-status" data-testid="claimable-status">Gold xStock · Solana</span><div className="pool-line"><span>Distribution basis</span><span data-testid="distribution-period">Pro rata holdings</span></div><Button disabled data-testid="claim-gldx-button" className="claim-button full-width"><LockKeyhole size={14}/>Claim GLDX</Button><p className="pool-disclaimer" data-testid="pool-disclaimer"><Info size={12}/>Your holding determines your share.<br/>Mining scores stay separate.</p></div></section>;
export default function Rewards(){
 const [data,setData]=useState<Reward|null>(null),[error,setError]=useState('');
 useEffect(()=>{request<Reward>('/rewards').then(setData).catch(()=>setError('Pool information could not be loaded. Please refresh.'));},[]);
 return <div className="page-content"><div className="page-title"><div><div className="eyebrow" data-testid="rewards-eyebrow">THE HOLDER POOL</div><h1 data-testid="rewards-title">Holder rewards<span>.</span></h1><p data-testid="rewards-intro">A proportional share for Agent Miner holders.</p></div><span className="neutral-badge" data-testid="reward-asset-badge"><Coins size={15}/>GLDX · Solana</span></div>
 {error&&<p className="error-banner" role="alert" data-testid="rewards-error">{error}</p>}
 <div className="reward-asset-note" data-testid="reward-asset-summary"><Coins size={25}/><div><strong data-testid="reward-asset-name">Gold xStock</strong><p data-testid="reward-asset-description">GLDX tracks SPDR Gold Shares. Game ore is not a financial asset.</p></div><span className="neutral-badge" data-testid="project-token-status">AGENT MINER · COMING</span></div>
 <div className="reward-metrics">{[{label:'Holder pool',icon:Coins,sub:'Allocated to holders'},{label:'Estimated rewards',icon:Clock3,sub:'Your proportional share'},{label:'Claimable GLDX',icon:Wallet,sub:'Finalized allocations'}].map((m,i)=><section key={m.label} data-testid={`reward-metric-${i}`}><div className="metric-top"><m.icon size={18}/><span>{m.label}</span></div><strong data-testid={`reward-value-${i}`}>—</strong><small>{m.sub}</small>{i===2&&<Button disabled className="claim-button" data-testid="rewards-claim-button"><LockKeyhole size={14}/>Claim GLDX</Button>}</section>)}</div>
 <div className="rewards-grid"><section className="formula-section"><div className="section-title"><Scale size={19}/><h2 data-testid="reward-formula-title">Your share of the pool</h2></div><p data-testid="reward-formula-description">Holder allocations are proportional to eligible Agent Miner holdings. Contest performance does not change the calculation.</p><div className="reward-formula" data-testid="reward-formula"><span>Your reward</span><b>=</b><span>Allocated pool</span><b>×</b><span className="fraction"><span>Your eligible holdings</span><span>Total eligible holdings</span></span></div><div className="principle-grid">{[['Hold without playing','Agent activity does not determine holder allocations.'],['Separate from scores','A higher contest rank does not increase your holder share.'],['No staking','Tokens stay in your wallet.'],['No fixed return','Rewards depend on the pool available for distribution.']].map(([title,text],i)=><div key={title} data-testid={`reward-principle-${i}`}><ShieldCheck size={16}/><strong>{title}</strong><p>{text}</p></div>)}</div></section>
 <section className="funding-section"><h2 data-testid="funding-title">Pool details</h2><dl>{[['Network','Solana'],['Reward asset','GLDX · Gold xStock'],['Project token','Agent Miner · Coming'],['Allocation','Pro rata holdings'],['Funding source','Allocated trading fees'],['Distributions',String(data?.transactions.length??0)]].map(([k,v],i)=><div key={k} data-testid={`funding-detail-${i}`}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{data?.platform_url&&<a href={data.platform_url} target="_blank" rel="noreferrer" data-testid="stock-reference-link" className="text-button">Stock.fun<ExternalLink size={13}/></a>}</section></div>
 <section className="separate-rewards" data-testid="separate-contest-rewards"><div className="section-title"><Trophy size={20}/><h2>Contest prizes</h2></div><p>Contest prizes have their own pool. Holder allocations are never used to fund the leaderboard.</p><Link className="text-button" to="/leaderboard" data-testid="rewards-contest-link">View the contest<ArrowUpRight size={14}/></Link></section>
 <section className="distribution-section"><div className="section-title"><ReceiptText size={18}/><h2 data-testid="distribution-title">Distribution ledger</h2><span className="neutral-badge" data-testid="distribution-count">{data?.transactions.length??0} distributions</span></div><div className="ledger-empty" data-testid="distribution-empty"><ReceiptText size={28}/><h3>No distributions yet</h3><p>There are no recorded allocations for this pool.</p></div></section><div className="reward-footnotes" data-testid="reward-risk-notice"><Info size={15}/><p>GLDX is a tokenized tracker, not direct ownership of physical gold or ETF shares. Eligibility is subject to issuer and jurisdiction restrictions. Rewards are not guaranteed.</p></div></div>;
}